---
title: "NRP72 -metadata - humann"
author: "Florentin Constancias"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document: 
    toc: yes
    keep_md: yes

---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
```

#### Load required packages

```{r,packages,message=FALSE}
library(tidyverse)
library(phyloseq)
library(microbiome)
library(here)
options(getClass.msg=FALSE) # https://github.com/epurdom/clusterExperiment/issues/66
#this fixes an error message that pops up because the class 'Annotated' is defined in two different packages
```


# Import phyloseq object

```{r}
ps = "data/raw/metabarcoding/ps_silva_dada2_humanonly.RDS"

ps %>% 
  here::here() %>%
  readRDS()  -> physeq

physeq$physeq -> physeq

physeq
```




```{r, eval=FALSE}
source("https://raw.githubusercontent.com/fconstancias/metabarcodingRpipeline/dev/scripts/functions_export_simplified.R")

# ps@sam_data = NULL

physeq %>%
  physeq_add_metadata(physeq = .,
                      metadata = here::here("data/raw/metabarcoding/Human_mapfile.xlsx") %>%
                        readxl::read_xlsx(), sample_column = "sample") -> physeq_meta

physeq;physeq_meta

physeq_meta %>% 
  saveRDS(here::here("data/raw/metabarcoding/ps_silva_dada2_humanonly_meta.RDS"))
```

```{r}
physeq_meta %>% 
  add_phylogeny_to_phyloseq(export = FALSE) %>% 
  saveRDS(here::here("data/raw/metabarcoding/ps_silva_dada2_humanonly_phylo_meta.RDS"))
```

```{r}

"data/raw/metabarcoding/ps_silva_dada2_humanonly_phylo_meta.RDS" %>% 
  here::here() %>% 
  readRDS() %>% 
  physeq_add_metadata(physeq = .,
                      metadata = here::here("data/raw/metabarcoding/Human_mapfile.xlsx") %>%
                        readxl::read_xlsx(), sample_column = "sample_name") %>% 
    saveRDS(here::here("data/raw/metabarcoding/ps_silva_dada2_humanonly_phylo_meta.RDS"))

  
  
```
```{r}
sessionInfo()
```

